// SPDX-License-Identifier: GPL-2.0
/*
 * test_chip_state.cpp  -  host-side known-answer tests for chip_state.cpp.
 *
 * Two kinds of ground truth used here, deliberately different from each
 * other so a bug in one doesn't hide behind the other:
 *
 *   1. The REAL captured KronosExtract.bin file (loaded from disk, not
 *      embedded/assumed) -- its magic/CRC/overlap must check out exactly
 *      as the real 188-byte file on disk, and the specific zone bytes this
 *      test asserts (0x19, 0x50) are cross-checked against a raw Python-
 *      style manual read of the same file (recorded in the comments).
 *   2. A fresh, from-scratch Python re-implementation of deax_step(),
 *      written independently from the same kronos_extract.c source this
 *      C++ port came from, to catch transcription bugs the port itself
 *      wouldn't reveal (the same technique used for cb32/Blowfish
 *      elsewhere in this project) -- see gen_deax_vectors.py alongside
 *      this file. Vectors below were generated by that script.
 */

#include <cstdio>
#include <cstring>
#include <cstdlib>
#include "../at88_chip.h"

static int g_fail;

static void check_eq(const char *label, unsigned int got, unsigned int want)
{
	if (got == want) {
		printf("  ok    %-55s 0x%x\n", label, got);
		return;
	}
	printf("  FAIL  %-55s got=0x%x want=0x%x\n", label, got, want);
	g_fail++;
}

static unsigned char *read_file(const char *path, unsigned int *outLen)
{
	FILE *f = fopen(path, "rb");
	if (!f)
		return nullptr;
	fseek(f, 0, SEEK_END);
	long sz = ftell(f);
	fseek(f, 0, SEEK_SET);
	unsigned char *buf = (unsigned char *)malloc((size_t)sz);
	if (fread(buf, 1, (size_t)sz, f) != (size_t)sz) {
		fclose(f);
		free(buf);
		return nullptr;
	}
	fclose(f);
	*outLen = (unsigned int)sz;
	return buf;
}

int main(void)
{
	printf("AT88VirtualChip chip_state known-answer test\n");
	printf("=============================================\n");

	printf("[1] Load the REAL captured KronosExtract.bin\n");
	unsigned int blobLen = 0;
	unsigned char *blob = read_file(
		"/home/share/KronosExtract/build/KronosExtract.bin", &blobLen);
	if (!blob) {
		printf("  FAIL  could not read KronosExtract.bin -- is the path still valid?\n");
		return 1;
	}
	check_eq("captured file length == 188", blobLen, 188);

	AT88ChipState chip;
	memset(&chip, 0, sizeof(chip));
	int rc = at88_chip_load_from_extract(&chip, blob, blobLen);
	check_eq("at88_chip_load_from_extract succeeds (rc==0)", (unsigned int)(rc == 0), 1);
	check_eq("chip.dataLoaded set", (unsigned int)chip.dataLoaded, 1);
	free(blob);

	printf("[2] Confirmed real zone bytes (hand-verified against the file directly)\n");
	/* python3 -c "d=open('KronosExtract.bin','rb').read(); print(d[8+0x19:8+0x20].hex())"
	 * -> [REDACTED-PUBLIC-ID] */
	unsigned char cfg19[7];
	rc = at88_chip_read_config(&chip, 0x19, 7, cfg19);
	check_eq("read_config(0x19,7) rc==0", (unsigned int)(rc == 0), 1);
	static const unsigned char want19[7] = {0x00,0x00,0x00,0x00,0x00,0x00,0x00};
	bool ok19 = memcmp(cfg19, want19, 7) == 0;
	check_eq("cfg[0x19..0x1f] == [REDACTED-PUBLIC-ID]", (unsigned int)ok19, 1);

	/* python3 -c "... print(d[8+0x50:8+0x58].hex())" -> [REDACTED-DEVICE-DATA] */
	unsigned char cfg50[8];
	rc = at88_chip_read_config(&chip, 0x50, 8, cfg50);
	check_eq("read_config(0x50,8) rc==0", (unsigned int)(rc == 0), 1);
	static const unsigned char want50[8] = {0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00};
	bool ok50 = memcmp(cfg50, want50, 8) == 0;
	check_eq("cfg[0x50..0x57] == [REDACTED-DEVICE-DATA]", (unsigned int)ok50, 1);

	printf("[3] Out-of-range config read rejected\n");
	unsigned char scratch[8];
	rc = at88_chip_read_config(&chip, 125, 8, scratch);	/* 125+8=133 > 128 */
	check_eq("read_config past the end returns nonzero", (unsigned int)(rc != 0), 1);

	printf("[4] Zone0 read/step self-consistency (encrypt with one DeaxState,\n"
	       "    decrypt with a freshly-seeded second one, recover the plaintext)\n");
	DeaxState chipSide, hostSide;
	deax_init(&chipSide);
	deax_init(&hostSide);
	unsigned char cipher[16];
	rc = at88_chip_read_zone0(&chip, &chipSide, 0, 16, cipher);
	check_eq("read_zone0(0,16) rc==0", (unsigned int)(rc == 0), 1);
	/* Host-side decrypt: same 12 pre-steps, then per-byte XOR-then-step-on-
	 * plaintext, exactly mirroring kronos_extract.c's synth_zone0_read(). */
	deax_step(&hostSide, 0); deax_step(&hostSide, 0); deax_step(&hostSide, 0);
	deax_step(&hostSide, 0); deax_step(&hostSide, 0);
	deax_step(&hostSide, 0);	/* addr=0 */
	deax_step(&hostSide, 0); deax_step(&hostSide, 0); deax_step(&hostSide, 0);
	deax_step(&hostSide, 0); deax_step(&hostSide, 0);
	deax_step(&hostSide, 16);	/* len=16 */
	unsigned char recovered[16];
	for (int i = 0; i < 16; i++) {
		recovered[i] = (unsigned char)(cipher[i] ^ hostSide.gpa);
		deax_step(&hostSide, recovered[i]);
		deax_step(&hostSide, 0); deax_step(&hostSide, 0); deax_step(&hostSide, 0);
		deax_step(&hostSide, 0); deax_step(&hostSide, 0);
	}
	bool roundTripOk = memcmp(recovered, chip.zone0, 16) == 0;
	check_eq("host-side decrypt recovers the real zone0 plaintext", (unsigned int)roundTripOk, 1);

	printf("[5] Out-of-range zone0 read rejected\n");
	DeaxState d2;
	deax_init(&d2);
	rc = at88_chip_read_zone0(&chip, &d2, 35, 8, scratch);	/* 35+8=43 > 40 */
	check_eq("read_zone0 past the end returns nonzero", (unsigned int)(rc != 0), 1);

	printf("[6] deax_step vs. an independent from-scratch Python re-implementation\n"
	       "    (gen_deax_vectors.py, written straight from kronos_extract.c, not\n"
	       "    from this C++ port -- catches transcription bugs the port alone can't)\n");
	DeaxState pyCheck;
	deax_init(&pyCheck);
	static const unsigned char pyInputs[12] = {
		0x00,0x00,0x00,0x00,0x00, 0x19, 0x00,0x00,0x00,0x00,0x00, 0x07
	};
	static const unsigned char pyExpectedGpa[12] = {
		0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00, 0x03, 0x30, 0x00
	};
	bool pyOk = true;
	for (int i = 0; i < 12; i++) {
		deax_step(&pyCheck, pyInputs[i]);
		if (pyCheck.gpa != pyExpectedGpa[i]) {
			printf("  FAIL  step %d: got gpa=0x%02x want=0x%02x\n",
			       i, pyCheck.gpa, pyExpectedGpa[i]);
			pyOk = false;
		}
	}
	check_eq("all 12 steps match the independent Python implementation", (unsigned int)pyOk, 1);

	printf("[7] at88_chip_load_synthetic() -- the VM/no-real-hardware fallback\n"
	       "    (sec 10.233): AAC bytes must start pre-saturated at 0xff, not 0,\n"
	       "    or the very first $B8 round can never report \"verified\" --\n"
	       "    confirmed via a real OA.ko<->AT88VirtualChip integration run.\n");
	AT88ChipState synth;
	memset(&synth, 0xaa, sizeof(synth));	/* poison first, same convention as the rest of this project */
	at88_chip_load_synthetic(&synth);
	check_eq("dataLoaded stays 0 (honestly not real per-device data)",
		 (unsigned int)synth.dataLoaded, 0);
	check_eq("configZone[0x50] (AAC, the only sel==0 slot ever read) == 0xff",
		 synth.configZone[0x50], 0xff);
	check_eq("configZone[0x19] (IdN) == 0 (synthetic, no real secret)", synth.configZone[0x19], 0);
	check_eq("zone0[0] == 0 (synthetic, no real secret -- NOT clobbered by an "
		 "out-of-bounds configZone[0x80] write)", synth.zone0[0], 0);
	check_eq("b8RoundsAccepted reset to 0", (unsigned int)synth.b8RoundsAccepted, 0);

	printf("=============================================\n");
	if (g_fail) {
		printf("RESULT: %d check(s) FAILED\n", g_fail);
		return 1;
	}
	printf("RESULT: all checks passed\n");
	return 0;
}
