// SPDX-License-Identifier: GPL-2.0
/*
 * test_eq_coefficients.cpp  -  KAT for ../src/engine/eq_coefficients.cpp,
 * CSTGEQ's five math functions (batch 30, sec 10.178).
 *
 * Golden values were generated by a from-scratch Python x87-stack
 * emulator that mechanically replays the exact objdump mnemonic+operand
 * stream for each function/branch (tracking FPU stack depth/position
 * exactly like real hardware) -- an INDEPENDENT derivation from the
 * inline-asm transcription in eq_coefficients.cpp, not copy-pasted from
 * it. Every branch combination was confirmed by that emulator to leave
 * the FPU stack at depth 0 on return before being used here.
 *
 * IMPORTANT precision note, found by this test the hard way: hardware
 * `fptan`/`fcos` are NOT guaranteed bit-identical to a software
 * `tan()`/`cos()` (they are transcendental approximations, not
 * correctly-rounded IEEE-754 ops like add/sub/mul/div). Any golden
 * value whose OWN computation chain depends on the transcendental
 * result (CalculateLowShelfBeta/CalculateHighShelfBeta/
 * CalculatePeakingBeta's return value, CalculatePeakingCoefficients's
 * b1) is checked with a small relative epsilon, not bit-exact.
 * Everything else (the byproduct *outOmega, CalculatePeakingCoefficients's
 * b0/b2/a1/a2, and ALL of CalculateShelvingCoefficients -- confirmed via
 * full disassembly to contain NO fcos/fptan at all) is pure add/sub/
 * mul/div/negate and is checked BIT-EXACT (raw uint32 reinterpretation).
 *
 * Second real bug this test caught pre-commit: the popping two-register
 * x87 forms (`fsubp`/`fsubrp`/`fdivp`/`fdivrp %st,%st(i)`) have their
 * "regular" vs "reverse" direction OPPOSITE to what analogy with the
 * non-popping `fsub %st(i),%st`-style forms would suggest -- confirmed
 * via a standalone hardware microtest, not just re-derived by hand a
 * second time. This only affected the Python emulator's own golden-value
 * generator (a plain semantic misunderstanding on the reconstructor's
 * part) -- the inline asm in eq_coefficients.cpp is an unchanged,
 * verbatim mnemonic-for-mnemonic transcription of the real disassembly
 * throughout, confirmed correct by cross-checking its actual compiled
 * behavior (gdb register inspection) against the corrected formula.
 */

#include <cstdio>
#include <cstring>
#include <cmath>
#include "oa_global.h"

static int g_fail;

static unsigned int bits(float f)
{
	unsigned int u;
	memcpy(&u, &f, sizeof(u));
	return u;
}

static void check_eq(const char *label, unsigned int got, unsigned int want)
{
	bool ok = got == want;
	if (!ok)
		g_fail++;
	printf("  %s  %-70s 0x%08x\n", ok ? "ok  " : "FAIL", label, got);
	if (!ok)
		printf("        (wanted 0x%08x)\n", want);
}

/* Relative-epsilon check for hardware-transcendental-derived values. */
static void check_close(const char *label, float got, float want)
{
	float diff = fabsf(got - want);
	float scale = fabsf(want) > 1.0f ? fabsf(want) : 1.0f;
	bool ok = diff <= scale * 1e-4f;
	if (!ok)
		g_fail++;
	printf("  %s  %-70s %.9g\n", ok ? "ok  " : "FAIL", label, (double)got);
	if (!ok)
		printf("        (wanted ~%.9g, diff=%.9g)\n", (double)want, (double)diff);
}

int main()
{
	printf("[1] CalculateLowShelfBeta / CalculateHighShelfBeta (epsilon: real fptan vs software tan())\n");
	{
		struct { float freq, lo, hi; } t[] = {
			{ 100.0f,   0.0065450784750282764f, 152.7884521484375f },
			{ 1000.0f,  0.06554346531629562f,   15.257064819335938f },
			{ 5000.0f,  0.3394542932510376f,    2.9459049701690674f },
			{ 12000.0f, 1.0f,                   1.0f }, /* Fs/4: both reduce to tan(pi/4) */
			{ 20.0f,    0.0013089977437630296f, 763.9453125f },
		};
		for (unsigned i = 0; i < sizeof(t)/sizeof(t[0]); i++) {
			char label[96];
			snprintf(label, sizeof(label), "LowShelfBeta(%g)", t[i].freq);
			check_close(label, CSTGEQ::CalculateLowShelfBeta(t[i].freq), t[i].lo);
			snprintf(label, sizeof(label), "HighShelfBeta(%g)", t[i].freq);
			check_close(label, CSTGEQ::CalculateHighShelfBeta(t[i].freq), t[i].hi);
		}
	}

	printf("[2] CalculatePeakingBeta -- byproduct *outOmega (bit-exact) + clamped tan() (epsilon)\n");
	{
		struct { float freq, bw, beta; unsigned int omega; } t[] = {
			{ 1000.0f, 0.5f,  0.13165250420570374f, 0x3e060a92u }, /* unclamped */
			{ 1000.0f, 2.0f,  0.03273661062121391f, 0x3e060a92u }, /* unclamped, different beta this time */
			{ 5000.0f, 0.1f,  12.706206321716309f,  0x3f278d37u }, /* clamped: x=omega/(2*bw) > threshold */
			{ 200.0f,  4.0f,  0.0032725040800869465f, 0x3cd67750u },
			{ 50.0f,   0.05f, 0.06554346531629562f, 0x3bd67750u },
		};
		for (unsigned i = 0; i < sizeof(t)/sizeof(t[0]); i++) {
			float omega = 0.0f;
			float beta = CSTGEQ::CalculatePeakingBeta(t[i].freq, t[i].bw, &omega);
			char label[96];
			snprintf(label, sizeof(label), "PeakingBeta(%g,%g) beta", t[i].freq, t[i].bw);
			check_close(label, beta, t[i].beta);
			snprintf(label, sizeof(label), "PeakingBeta(%g,%g) *outOmega", t[i].freq, t[i].bw);
			check_eq(label, bits(omega), t[i].omega);
		}
		/* (5000,0.1) hits the clamp (x = 0.6545/0.2 = 3.27 > 1.49225652);
		 * confirm a LARGER bw (narrower x) on the SAME freq moves off the
		 * clamp and gives a materially different beta. */
		float o1, o2;
		float b1 = CSTGEQ::CalculatePeakingBeta(5000.0f, 0.1f, &o1);
		float b2 = CSTGEQ::CalculatePeakingBeta(5000.0f, 5.0f, &o2);
		check_eq("clamped case matches the threshold-clamped constant", 1,
			 (unsigned int)(fabsf(b1 - tanf(1.49225652217865f)) < 1e-4f));
		check_eq("larger bw moves off the clamp (different, smaller beta)", 1,
			 (unsigned int)(b2 < b1));
	}

	printf("[3] CalculatePeakingCoefficients -- both p0>=1.0 and p0<1.0 branches\n");
	{
		struct { float p0, p1, p2; unsigned int b0; float b1; unsigned int b2, a1, a2; } t[] = {
			{ 2.0f, 0.5f, 0.5f, 0x3faaaaabu, -1.1701101064682007f, 0x00000000u, 0x3f95c62bu, 0xbeaaaaabu },
			{ 0.5f, 0.5f, 0.5f, 0x3f400000u, -0.8775825500488281f, 0x3e800000u, 0x3f60a940u, 0x80000000u },
			{ 2.0f, 0.2f, 1.0f, 0x3f955555u, -0.9005038142204285f, 0x3f000000u, 0x3f66876bu, 0xbf2aaaabu },
			{ 0.3f, 0.3f, 0.7f, 0x3f266666u, -0.7648422122001648f, 0x3eb33333u, 0x3f43ccb3u, 0x80000000u },
			{ 1.0f, 0.5f, 0.5f, 0x3f800000u, -1.1701101064682007f, 0x3eaaaaabu, 0x3f95c62bu, 0xbeaaaaabu },
			{ 1.0f, 0.5f, 1.2f, 0x3f800000u, -0.4831436276435852f, 0x3eaaaaabu, 0x3ef75e9au, 0xbeaaaaabu },
		};
		for (unsigned i = 0; i < sizeof(t)/sizeof(t[0]); i++) {
			STGEQCoefficients out;
			memset(&out, 0xCC, sizeof(out));
			CSTGEQ::CalculatePeakingCoefficients(t[i].p0, t[i].p1, t[i].p2, &out);
			char label[96];
			snprintf(label, sizeof(label), "PeakCoef(%g,%g,%g) b0", t[i].p0, t[i].p1, t[i].p2);
			check_eq(label, bits(out.b0), t[i].b0);
			snprintf(label, sizeof(label), "PeakCoef(%g,%g,%g) b1 (cos-dependent)", t[i].p0, t[i].p1, t[i].p2);
			check_close(label, out.b1, t[i].b1);
			snprintf(label, sizeof(label), "PeakCoef(%g,%g,%g) b2", t[i].p0, t[i].p1, t[i].p2);
			check_eq(label, bits(out.b2), t[i].b2);
			snprintf(label, sizeof(label), "PeakCoef(%g,%g,%g) a1", t[i].p0, t[i].p1, t[i].p2);
			check_eq(label, bits(out.a1), t[i].a1);
			snprintf(label, sizeof(label), "PeakCoef(%g,%g,%g) a2", t[i].p0, t[i].p1, t[i].p2);
			check_eq(label, bits(out.a2), t[i].a2);
		}
	}

	printf("[4] CalculateShelvingCoefficients -- all 4 (gain>=1/<1) x (type) combinations (bit-exact: no fcos/fptan at all)\n");
	{
		struct { float gain, beta; int type; unsigned int b0,b1,b2,a1,a2; } t[] = {
			{ 2.0f, 0.5f, 0, 0x3faaaaabu, 0x80000000u, 0x00000000u, 0x3eaaaaabu, 0x00000000u },
			{ 2.0f, 0.5f, 1, 0x3faaaaabu, 0x00000000u, 0x00000000u, 0xbeaaaaabu, 0x00000000u },
			{ 0.5f, 0.5f, 0, 0x3f400000u, 0xbe800000u, 0x00000000u, 0x00000000u, 0x00000000u },
			{ 0.5f, 0.5f, 1, 0x3f400000u, 0x3e800000u, 0x00000000u, 0x80000000u, 0x00000000u },
			{ 1.0f, 0.5f, 0, 0x3f800000u, 0xbeaaaaabu, 0x00000000u, 0x3eaaaaabu, 0x00000000u },
			{ 1.0f, 0.5f, 1, 0x3f800000u, 0x3eaaaaabu, 0x00000000u, 0xbeaaaaabu, 0x00000000u },
			{ 0.3f, 1.5f, 0, 0x3ed55556u, 0x3daaaaabu, 0x00000000u, 0xbf2aaaaau, 0x00000000u },
			{ 0.3f, 1.5f, 1, 0x3ed55556u, 0xbdaaaaabu, 0x00000000u, 0x3f2aaaaau, 0x00000000u },
			{ 5.0f, 0.1f, 0, 0x3fae8ba3u, 0xbee8ba2eu, 0x00000000u, 0x3f51745du, 0x00000000u },
			{ 5.0f, 0.1f, 1, 0x3fae8ba3u, 0x3ee8ba2eu, 0x00000000u, 0xbf51745du, 0x00000000u },
		};
		for (unsigned i = 0; i < sizeof(t)/sizeof(t[0]); i++) {
			STGEQCoefficients out;
			memset(&out, 0xCC, sizeof(out));
			eEQShelvingType type = (eEQShelvingType)t[i].type;
			CSTGEQ::CalculateShelvingCoefficients(t[i].gain, t[i].beta, type, &out);
			char label[96];
			snprintf(label, sizeof(label), "ShelvCoef(%g,%g,type=%d) b0", t[i].gain, t[i].beta, t[i].type);
			check_eq(label, bits(out.b0), t[i].b0);
			snprintf(label, sizeof(label), "ShelvCoef(%g,%g,type=%d) b1", t[i].gain, t[i].beta, t[i].type);
			check_eq(label, bits(out.b1), t[i].b1);
			snprintf(label, sizeof(label), "ShelvCoef(%g,%g,type=%d) b2", t[i].gain, t[i].beta, t[i].type);
			check_eq(label, bits(out.b2), t[i].b2);
			snprintf(label, sizeof(label), "ShelvCoef(%g,%g,type=%d) a1", t[i].gain, t[i].beta, t[i].type);
			check_eq(label, bits(out.a1), t[i].a1);
			snprintf(label, sizeof(label), "ShelvCoef(%g,%g,type=%d) a2", t[i].gain, t[i].beta, t[i].type);
			check_eq(label, bits(out.a2), t[i].a2);
		}
		/* Cross-check: for a given (gain,beta), type only ever changes the
		 * SIGN of exactly one of b1/a1, never b0/b2/a2. */
		STGEQCoefficients o0, o1;
		CSTGEQ::CalculateShelvingCoefficients(2.0f, 0.5f, kEQLowShelf, &o0);
		CSTGEQ::CalculateShelvingCoefficients(2.0f, 0.5f, kEQHighShelf, &o1);
		check_eq("type doesn't affect b0", bits(o0.b0), bits(o1.b0));
		check_eq("type doesn't affect b2", bits(o0.b2), bits(o1.b2));
		check_eq("type doesn't affect a2", bits(o0.a2), bits(o1.a2));
	}

	printf("%s (%d failed check%s)\n", g_fail ? "FAILED" : "all checks passed",
	       g_fail, g_fail == 1 ? "" : "s");
	return g_fail ? 1 : 0;
}
