// SPDX-License-Identifier: GPL-2.0
/*
 * test_crypto.cpp  -  host-side known-answer tests for the Stage-2 crypto
 * primitives (moancjsd82 / Blowfish-CFB-64, DecodeBytesFromAscii / Crockford
 * Base-32).
 *
 * Vectors are anchored to independent sources, not just self-consistency:
 *
 *   - Blowfish-CFB-64: key/iv taken from `UIAppGen.Tests/TestHelpers.cs`'s
 *     `ExsData` (real hardware-extracted AT88 chip data, from
 *     `KronosExtract/build/KronosExtract.bin`), ciphertext taken from
 *     `UIAppGen.Tests/BlowfishCfb64Tests.cs`'s
 *     `Encrypt_KnownVector_MatchesPython` test, which was itself checked
 *     against the independent Python reference `KronosExtract/build/kronos.py`.
 *     This proves moancjsd82() against a second, independently-implemented
 *     tool chain (C#/BouncyCastle), not just against itself.
 *
 *   - Crockford Base-32: vector generated by an independent from-scratch
 *     Python implementation of the confirmed algorithm (not copied from any
 *     existing tool in this repo), during this reconstruction pass -- proves
 *     DecodeBytesFromAscii() against a third, independent implementation.
 *
 *   - MD5: the official RFC 1321 Appendix A.5 test suite -- the standard,
 *     universally-published reference vectors for this algorithm.
 *
 * Build & run:  see Makefile `verify/test_crypto` target.
 */

#include <cstdio>
#include <cstring>
#include "oa_crypto.h"
#include "oa_md5.h"

static int g_fail;

static void hex_to_bytes(const char *hex, unsigned char *out, unsigned int n)
{
	for (unsigned int i = 0; i < n; i++) {
		unsigned int byte;
		sscanf(hex + i * 2, "%2x", &byte);
		out[i] = (unsigned char)byte;
	}
}

static void check_bytes(const char *label, const unsigned char *got, const unsigned char *want, unsigned int n)
{
	if (memcmp(got, want, n) == 0) {
		printf("  ok    %s\n", label);
		return;
	}
	printf("  FAIL  %s\n", label);
	printf("        got : ");
	for (unsigned int i = 0; i < n; i++) printf("%02x", got[i]);
	printf("\n        want: ");
	for (unsigned int i = 0; i < n; i++) printf("%02x", want[i]);
	printf("\n");
	g_fail++;
}

/* [1] moancjsd82 (Blowfish-CFB-64) against the C#/BouncyCastle + Python-checked vector */
static void test_moancjsd82_known_vector(void)
{
	printf("[1] moancjsd82 (Blowfish-CFB-64) vs. C#/Python cross-checked vector\n");

	unsigned char chipKeyMaterial[24];
	hex_to_bytes("0d125e1211d861e9100d0973e876089f", chipKeyMaterial, 16);      /* key */
	hex_to_bytes("5c293c97e3c2dcc1", chipKeyMaterial + 16, 8);                  /* iv  */

	unsigned char ciphertext[15];
	hex_to_bytes("70fc9debdb11137898827b4b661197", ciphertext, 15);

	static const unsigned char expected[15] =
		{ 'H','e','l','l','o',' ','K','r','o','n','o','s','!','!','\0' };

	unsigned char plainOut[15];
	int rc = moancjsd82(chipKeyMaterial, ciphertext, 15, plainOut);

	if (rc != 15) {
		printf("  FAIL  moancjsd82 returned %d, expected 15\n", rc);
		g_fail++;
	}
	check_bytes("decrypt(\"Hello Kronos!!\\0\") ciphertext -> plaintext", plainOut, expected, 15);
}

/* NOTE: no "encrypt via moancjsd82 then decrypt via moancjsd82" round-trip
 * test here. moancjsd82's real, hardware-confirmed role is DECODE ONLY --
 * valid auth strings are always generated externally (kronos_auth.py, on a
 * PC), never encoded on-device. In CFB mode, the feedback register is fed
 * from the *ciphertext* regardless of direction, which differs depending on
 * which buffer (input vs. computed output) is actually the ciphertext --
 * calling this decode-shaped function to simulate an encrypt step feeds the
 * wrong buffer into that register for anything past the first block. That's
 * a property of testing outside the function's real contract, not a decode
 * bug (test [1] above, the real hardware-derived vector, already proves the
 * decode path bit-exact against an independent tool chain).*/

/* [2] DecodeBytesFromAscii (Crockford Base-32) against an independent Python vector */
static void test_decode_bytes_from_ascii(void)
{
	printf("[2] DecodeBytesFromAscii (Crockford Base-32) vs. independent Python vector\n");

	static const unsigned char expected[15] =
		{ 0x01,0x02,0x03,0x04,0x05,0x06,0x07,0x08,0x09,0x0a,0x0b,0x0c,0x0d,0x0e,0x0f };

	unsigned char out[15];
	int rc = DecodeBytesFromAscii(out, "0H1H40851440F1HA1R6HR2RG");

	if (rc != 0) {
		printf("  FAIL  DecodeBytesFromAscii returned %d, expected 0\n", rc);
		g_fail++;
	}
	check_bytes("cb32 decode(\"0H1H40851440F1HA1R6HR2RG\")", out, expected, 15);

	/* Dashes and lowercase must be accepted transparently (real auth strings
	 * are displayed dashed, e.g. "QH55-08W6-Y03J-..."). */
	unsigned char out2[15];
	rc = DecodeBytesFromAscii(out2, "0h1h-4085-1440-f1ha-1r6h-r2rg");
	if (rc != 0) {
		printf("  FAIL  dashed/lowercase decode returned %d, expected 0\n", rc);
		g_fail++;
	}
	check_bytes("cb32 decode is dash/case-insensitive", out2, expected, 15);
}

/* [3] md5_init/append/finish against the official RFC 1321 Appendix A.5 test suite */
static void md5_of_string(const char *s, unsigned char digest[16])
{
	struct md5_state_t ctx;
	md5_init(&ctx);
	md5_append(&ctx, (const unsigned char *)s, (int)strlen(s));
	md5_finish(&ctx, digest);
}

static void test_md5_rfc1321_vectors(void)
{
	printf("[3] md5 vs. official RFC 1321 Appendix A.5 test suite\n");

	static const struct { const char *input; const char *hexDigest; } vectors[] = {
		{ "",                                  "d41d8cd98f00b204e9800998ecf8427e" },
		{ "a",                                 "0cc175b9c0f1b6a831c399e269772661" },
		{ "abc",                               "900150983cd24fb0d6963f7d28e17f72" },
		{ "message digest",                    "f96b697d7cb7938d525a2f31aaf161d0" },
		{ "abcdefghijklmnopqrstuvwxyz",        "c3fcd3d76192e4007dfb496cca67e13b" },
		{ "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789",
		                                       "d174ab98d277d9f5a5611c2c9f419d9f" },
		{ "12345678901234567890123456789012345678901234567890123456789012345678901234567890",
		                                       "57edf4a22be3c955ac49da2e2107b67a" },
	};

	for (unsigned int i = 0; i < sizeof vectors / sizeof vectors[0]; i++) {
		unsigned char expected[16], got[16];
		hex_to_bytes(vectors[i].hexDigest, expected, 16);
		md5_of_string(vectors[i].input, got);

		char label[64];
		snprintf(label, sizeof label, "md5(len=%u)", (unsigned int)strlen(vectors[i].input));
		check_bytes(label, got, expected, 16);
	}

	/* Also exercise the multi-block/partial-buffer path (RFC vectors above
	 * are all under one 64-byte block once padded). */
	char big[200];
	for (int i = 0; i < 200; i++)
		big[i] = (char)('A' + (i % 26));
	unsigned char digest1[16], digest2[16];

	struct md5_state_t ctx;
	md5_init(&ctx);
	md5_append(&ctx, (const unsigned char *)big, 200);
	md5_finish(&ctx, digest1);

	/* Same data, fed in three uneven chunks -- must produce the identical digest. */
	md5_init(&ctx);
	md5_append(&ctx, (const unsigned char *)big, 13);
	md5_append(&ctx, (const unsigned char *)big + 13, 64);
	md5_append(&ctx, (const unsigned char *)big + 77, 200 - 77);
	md5_finish(&ctx, digest2);

	check_bytes("md5 chunked-append matches single-call append", digest2, digest1, 16);
}

int main(void)
{
	printf("OA Stage-2 crypto known-answer tests\n");
	printf("=====================================\n");
	test_moancjsd82_known_vector();

	test_decode_bytes_from_ascii();
	test_md5_rfc1321_vectors();
	printf("=====================================\n");
	if (g_fail) {
		printf("RESULT: %d check(s) FAILED\n", g_fail);
		return 1;
	}
	printf("RESULT: all checks passed\n");
	return 0;
}
