// SPDX-License-Identifier: GPL-2.0
/*
 * atmel_challenge.cpp  -  cm_ComputeChallenge() (batch 55).
 *
 * Ground truth: `sdflkjsvnd2g`, .text+0x4f61c0, 1386 bytes. Confirmed
 * real ground-truth identity via SetupAtmelForAuthorizations()'s own
 * call site (.text+0x207b39: eax=chipConfig ptr / edx=sel=0 / ecx=
 * gpaKeyOut ptr -- matches this project's own already-declared
 * oa_atmel.h signature `cm_ComputeChallenge(chipConfig, sel, gpaKeyOut)`
 * exactly, regparm(3): eax/edx/ecx in that argument order).
 *
 * A pure GMP bignum computation -- unlike its four siblings closed this
 * same batch (cm_SetUserZone/nv2ac_dispatch_cmd/nv2ac_enable_cipher/
 * nv2ac_enable_encrypt, src/auth/nv2ac_handshake.cpp + atmel_zone_io.cpp),
 * it makes ZERO calls to stgNV2AC_sync_cmd/stgNV2AC_sync_read_cmd.
 * bar2_stubs_c.cpp's own prior header comment describing ALL FIVE of
 * these functions as "thin forwarders" over the AT88 driver was WRONG
 * for this one specifically -- corrected here after full independent
 * disassembly (not re-cited from that comment).
 *
 * Full derivation (confirmed via objdump -dr, every __gmpz_* call site
 * traced with its own register-sourced arguments):
 *
 *   1. Bounds check: strlen(P)+strlen(G)+1 <= 0x40 AND
 *      strlen(P)+strlen(Q)+1 <= 0x40, else return -1. (P/G/Q are the
 *      three GPA Diffie-Hellman decimal-string globals cm_SetChallengeParams
 *      already caches, atmel_primitives.cpp -- real ground-truth .bss
 *      layout is P/G/Q, NOT P/Q/G, per that file's own header comment.)
 *   2. mpzC = bignum(strcat(P,G), base 10); mpzD = bignum(strcat(P,Q),
 *      base 10) -- two independent moduli built by literal decimal-
 *      string concatenation (not numeric addition/multiplication),
 *      confirmed via the real lods/stos strcpy+repnz-scas-then-append
 *      strcat idiom in the disassembly.
 *   3. mpzB = chipConfig[6..0] accumulated as `mpzB = mpzB*256 + byte`,
 *      seven times, processing index 6 first down to index 0 (i.e.
 *      chipConfig[0] ends up as the LEAST significant byte of a 7-byte
 *      little-endian value); then mpzB = mpzB * mpzB (squared).
 *   4. mpzA = 1 << ((sel+17)*128). NOT bounds-checked here (unlike the
 *      sibling nv2ac_enable_cipher/encrypt, which DO reject sel>3) --
 *      ground truth has no such check in this function; preserved
 *      faithfully (relies on the caller only ever passing sel=0, which
 *      SetupAtmelForAuthorizations()'s own single real call site does).
 *   5. 16-byte output loop: 16 outer iterations x 8 inner bit-extraction
 *      steps (128 total). Each inner step:
 *        mpzA = (mpzA << 1) mod mpzC;
 *        mpzE = mpzB ^ mpzA  mod mpzD    (powm: base=mpzB, exp=mpzA, mod=mpzD);
 *        bit  = LSB(mpzE)  (0 if mpzE == 0, i.e. _mp_size == 0);
 *        outBuf[outer] |= bit << bitPos;
 *      (outBuf is a 16-byte scratch buffer, zeroed before the loop --
 *      ground truth's own outer-loop bound is a compiler-emitted
 *      END-POINTER comparison against `&mpzE`, which happens to sit
 *      exactly 16 bytes past the start of this scratch buffer in the
 *      real stack frame -- confirmed by hex arithmetic, not assumed;
 *      represented here as a plain `for (outer = 0; outer < 16; outer++)`
 *      since the pointer-vs-counter distinction has no observable
 *      behavioral difference.)
 *   6. Output copy -- CONFIRMED REAL, NOT a transcription slip: only 8
 *      of the 16 generated bytes are copied to gpaKeyOut, and NOT
 *      contiguously: outBuf[1,2,3,5,7,11,13,15] map to gpaKeyOut[0..7]
 *      in that order (outBuf[0,4,6,8,9,10,12,14] are silently
 *      discarded). Preserved exactly as ground truth's own real, sparse
 *      selection -- independently re-derived byte-by-byte from the
 *      disassembly's own eight `movzbl`/`mov %al,N(%edx)` pairs; no
 *      "nicer" arithmetic pattern was found in it, and none is assumed.
 *   7. Return 0 (ground truth: `xor ebx,ebx` then falls into the same
 *      shared success-return tail the two early-length-check failures
 *      use for -1, `mov ebx,eax`).
 *
 * __gmpz_* remain legitimate externals here exactly as in ground truth
 * (see include/oa_gmp.h's own header comment for the full derivation of
 * why, and STGGmp.ko as the real provider). This function's own logic
 * has NO branch depending on the actual numeric GPA result (steps 3-6
 * above are unconditional once the two length checks pass) -- so a
 * host KAT proving this exact call sequence/buffer shape runs to
 * completion and returns 0 does not require bit-exact GMP semantics,
 * only a bignum implementation that does not crash/hang (see
 * verify/test_atmel_setup.cpp's own header comment).
 */

#include "oa_atmel.h"
#include "oa_gmp.h"

extern "C" unsigned long strlen(const char *s);
extern "C" char *strcpy(char *dst, const char *src);

extern "C" const char *gGpaChallengeP;
extern "C" const char *gGpaChallengeG;
extern "C" const char *gGpaChallengeQ;

/*
 * Ground truth does NOT call an external strcat -- its own strcat-shaped
 * step is an inlined `repnz scas` (find the nul terminator) followed by
 * a `lods`/`stos` byte-copy loop (confirmed via disassembly, this file's
 * own header comment). strcpy IS a genuine ground-truth external
 * (confirmed `U` in ground truth's own `nm -u` too) so it's used as-is;
 * `strcat` is reproduced here manually rather than calling the libc
 * routine, so this reconstruction does not introduce an unresolved
 * symbol ground truth itself never has.
 */
static void AppendStr(char *dst, const char *src)
{
	char *end = dst;
	while (*end)
		end++;
	while ((*end++ = *src++) != 0)
		;
}

int cm_ComputeChallenge(const unsigned char *chipConfig, int sel, unsigned char *gpaKeyOut)
{
	if (strlen(gGpaChallengeP) + strlen(gGpaChallengeG) + 1 > 0x40)
		return -1;
	if (strlen(gGpaChallengeP) + strlen(gGpaChallengeQ) + 1 > 0x40)
		return -1;

	char catBuf[0x40];
	oa_mpz_t mpzC, mpzD, mpzB, mpzA, mpzE;

	strcpy(catBuf, gGpaChallengeP);
	AppendStr(catBuf, gGpaChallengeG);
	__gmpz_init_set_str(mpzC, catBuf, 10);

	strcpy(catBuf, gGpaChallengeP);
	AppendStr(catBuf, gGpaChallengeQ);
	__gmpz_init_set_str(mpzD, catBuf, 10);

	__gmpz_init(mpzB);
	for (int i = 6; i >= 0; i--) {
		__gmpz_mul_2exp(mpzB, mpzB, 8);
		__gmpz_add_ui(mpzB, mpzB, chipConfig[i]);
	}
	__gmpz_mul(mpzB, mpzB, mpzB);

	__gmpz_init_set_ui(mpzA, 1);
	__gmpz_mul_2exp(mpzA, mpzA, (unsigned long)((sel + 17) * 128));

	__gmpz_init(mpzE);

	unsigned char outBuf[16];
	for (int i = 0; i < 16; i++)
		outBuf[i] = 0;

	for (int outer = 0; outer < 16; outer++) {
		unsigned char byteVal = 0;
		for (int bitPos = 0; bitPos < 8; bitPos++) {
			__gmpz_mul_2exp(mpzA, mpzA, 1);
			__gmpz_tdiv_r(mpzA, mpzA, mpzC);
			__gmpz_powm(mpzE, mpzB, mpzA, mpzD);
			if (mpzE->_mp_size != 0 && (mpzE->_mp_d[0] & 1))
				byteVal = (unsigned char)(byteVal | (1u << bitPos));
		}
		outBuf[outer] = byteVal;
	}

	__gmpz_clear(mpzD);
	__gmpz_clear(mpzC);
	__gmpz_clear(mpzA);
	__gmpz_clear(mpzB);
	__gmpz_clear(mpzE);

	gpaKeyOut[0] = outBuf[1];
	gpaKeyOut[1] = outBuf[2];
	gpaKeyOut[2] = outBuf[3];
	gpaKeyOut[3] = outBuf[5];
	gpaKeyOut[4] = outBuf[7];
	gpaKeyOut[5] = outBuf[11];
	gpaKeyOut[6] = outBuf[13];
	gpaKeyOut[7] = outBuf[15];

	return 0;
}
